name: coollocalizations_generator
environment:
  sdk: ">=3.13.2 <4.0.0"

publish_to: none

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  intl: ^0.20.3
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.16.1
  coolint: ^3.0.0
