name: coollocalizations
environment:
  sdk: ">=3.2.4 <4.0.0"
publish_to: none

dependencies:
  json_annotation: 4.8.1
  intl: any

dev_dependencies:
  coolint: 1.0.1
  build_runner: any
  json_serializable: ^6.6.2
