name: coollocalizations
environment:
  sdk: ">=3.2.4 <4.0.0"
publish_to: none

dependencies:
  json_annotation: ^4.9.0
  intl: any

dev_dependencies:
  coolint: 2.0.0
  build_runner: any
  json_serializable: ^6.6.2
